import React from 'react';
import Header from '../components/Header';
import Footer from '../components/Footer';
import { useEffect } from 'react';

const Policy = () => {

  useEffect(()=>{
    window.scrollTo(0, 0);
  },[]);

  return (
    <>
        <Header />
        <section className='pt-5 mt-5 policy'>
            <div className='container'>
                <div className='policy-content'>
                    <h2 className='fw-8 mb-3 fs-1'>Fiverr's Privacy Policy</h2>
                    <p className='text-secondary lead' style={{letterSpacing: '2px'}}>Last update: Augest 01, 2023</p>
                    <p className='text-secondary lead' style={{letterSpacing: '2px'}}>Please read this privacy policy (the “ <span className='text-dark fw-8'>Policy</span> ”) carefully to understand how Fiverr International Ltd., 8 Kaplan St., Tel Aviv, Israel (“<span className='text-dark fw-8'>Fiverr</span>”, “<span className='text-dark fw-8'>we</span>”) uses personal information. By accessing or using www.fiverr.com, the Fiverr mobile app, or any other related sites, applications, services and goods, or any other website operated by Fiverr that links to this policy (each, the “<span className='text-dark fw-8'>Site</span>”), you acknowledge that you have read and understood this Policy. This Policy may change from time to time; any changes we make to this Policy will be posted on this Site, we will also take any other steps, to the extent required by applicable law, including notifying you about material changes. Changes to this Policy are effective as of the stated "<span className='text-dark fw-8'>Last Updated</span>" date. We recommend that you check the Policy periodically for any updates or changes.</p>
                    <h3 className='fw-8 fs-2 mb-3'>The short version</h3>
                    <p className='text-secondary lead' style={{letterSpacing: '2px'}}><span className='fw-8 fs-4 text-secondary'>Information We Collect -</span> You directly provide us with most of the information we collect: when you register to the Site, use it, complete forms, or register to any of our programs. We also collect information about your communications with Fiverr as well as any of your posts on our blogs or forums and your communication with other users of Fiverr. In addition, we automatically collect information while you access, browse, view or otherwise use the Site and receive information from third party vendors or other available sources.</p>
                    <p className='text-secondary lead' style={{letterSpacing: '2px'}}><span className='fw-8 fs-4 text-secondary'>Our Legal Basis for Using Your Personal Information -</span> Where relevant under applicable laws, all processing of your personal information will be justified by a "lawful ground" for processing as detailed below.</p>
                    <p className='text-secondary lead' style={{letterSpacing: '2px'}}><span className='fw-8 fs-4 text-secondary'>How Do We Use the Information Collected? -</span> We use personal information to provide you with quality service and security, to operate the Site, understand how people use the Site, and to perform our obligations to you; to ensure marketplace integrity and security; to prevent fraud; to contact you and send you direct marketing communications; to promote and advertise the Site, our services and the Fiverr marketplace; to comply with lawful requests by public authorities and to comply with applicable laws and regulations.</p>
                    <h3 className='fw-8 fs-2 mb-3'>Information We Collect</h3>
                    <p className='text-secondary lead' style={{letterSpacing: '2px'}}><span className='fw-8 fs-4 text-secondary'>Information You Provide -</span> When you register to the Site, use it, complete forms, participate in skills tests or surveys, or use the Site as collaborator, and/or register to our affiliate or influencer or similar program, we ask you to provide certain personal information, including a valid email address, Facebook or Google account login details and username. We will also ask you to provide or otherwise collect additional information, such as, your name, profile details, physical address or billing information, telephone number or other contact details, transactional information, payment information (for example, in certain cases we process your payment method and credit card number), taxpayer information and forms, details about other social networks linked accounts, details about your listed gigs, purchases, education, profession and expertise, information and files uploaded by you to the Site, and additional authentication information (such as copies of your government issued ID, passport, or driving license, as permitted by applicable laws and as detailed in our Seller Help Center at “Verifying Your Identity”). We also collect information about or contained in your communications with Fiverr as well as any of your posts on our blogs or forums and your communication with other users of Fiverr.</p>
                    <h3 className='fw-8 fs-2 mb-3'>Specific Provisions for California Residents</h3>
                    <p className='text-secondary lead' style={{letterSpacing: '2px'}}>This Site is offered and available to users who are at least 18 years of age or older and of legal age to form a binding contract. Minors under 18 and at least 13 years of age, are only permitted to use the Site through an account owned by a parent or legal guardian with their appropriate permission. Minors under 13 are not permitted to use the Site or the Fiverr services. We do not knowingly collect personal information from children under 13. Parents and guardians should at all times supervise their children's activities. If we learn we have collected or received personal information from a child under 13, we will delete that personal information. If you believe we might have any information from or about a child under 13, please contact us at privacy@fiverr.com.</p>
                    <h3 className='fw-8 fs-2 mb-3'>Updating Personal Information</h3>
                    <p className='text-secondary lead' style={{letterSpacing: '2px'}}>With social media partners. Our Site includes certain social media features, including single sign on features. We also share limited personal information with such social media platforms and marketing partners, such as Facebook and Google, to promote our services or the Fiverr marketplace. Such features and third party services collect certain information about you and may set a cookie to enable their functionality. Such third parties’ features are governed by their policies.</p>
                    <h3 className='fw-8 fs-2 mb-3'>Contact Us</h3>
                    <p className='text-secondary lead' style={{letterSpacing: '2px'}}>Under certain circumstances, you may have the right to object, on grounds relating to your particular situation, to the processing of your personal data by us and we may be required to no longer process your personal data. Moreover, if your personal data is processed for direct marketing purposes, you have the right to object at any time to the processing of personal data concerning you for such marketing, which includes profiling to the extent that it is related to such direct marketing. In this case your personal data will no longer be processed for such purposes by us. In addition to the above, you have the right to lodge a complaint with a supervisory authority for data protection. Please note that the right of access and the right to erasure do not constitute absolute rights and the interests of other individuals may restrict your right of access or erase in accordance with local laws. We will ask you for additional data to confirm your identity and for security purposes, before disclosing data requested by you. We reserve the right to charge a fee where permitted by law. We will decline to process requests that jeopardize the privacy of others, are extremely impractical, or would cause us to take any action that is not permissible under applicable laws. Additionally, as permitted by applicable laws, we will retain where necessary certain personal information for a limited period of time for record-keeping, accounting and fraud prevention purposes.</p>
                </div>
            </div>
        </section>
        <Footer />
    </>
  )
}

export default Policy;